api_prefix: $API_PREFIX
api_key: $API_KEY
base_url_search: $BASE_URL_SEARCH
base_url_ingest: $BASE_URL_INGEST
base_url_embedding: $BASE_URL_EMBEDDING
models:
  - jina-embeddings-v2-base-de-4096: sentence_transformers/jina-embeddings-v2-base-de-4096
  - jina-embeddings-v2-base-de-128: sentence_transformers/jina-embeddings-v2-base-de-128
bucket_name: $BUCKET_NAME
bucket_path: $BUCKET_PATH
service_account: $SERVICE_ACCOUNT|
local_model_path: $LOCAL_MODEL_PATH
