#
# UI Constants
#
UI_CONFIG_KEY = "ui_config"
UI_CONFIG_TITLE_KEY = "title"
UI_CONFIG_LOGO_KEY = "logo"
UI_CONFIG_HEADER_BACKGROUND_COLOR_KEY = "header_background"
UI_CONFIG_CUSTOM_CSS_KEY = "custom_css"

# Text Input
TEXT_INPUT_PLACEHOLDER_KEY = "placeholder"
TEXT_INPUT_LABEL_KEY = "label"
TEXT_INPUT_VALIDATOR_KEY = "validator_function"
TEXT_INPUT_ACCESSOR_KEY = "accessor_function"
TEXT_INPUT_HAS_PAGING_KEY = ""
TEXT_INPUT_URL_PARAMETER_KEY = "url_parameter"

# Multi Select
MULTI_SELECT_LABEL_KEY = "label"
MULTI_SELECT_ITEM_DEFAULTS_KEY = "get_item_defaults"
MULTI_SELECT_OPTION_VALUE_KEY = "value"
MULTI_SELECT_OPTIONS_DEFAULT_FUNCTION_KEY = "option_default"
MULTI_SELECT_REGISTER_AS_KEY = "register_as"
MULTI_SELECT_LINKED_FILTER_NAME_KEY = "linked_filter_name"
MULTI_SELECT_FILTER_CATEGORY = "filter_category"
MULTI_SELECT_DISPLAY_NAME_KEY = "name"
MULTI_SELECT_OPTIONS_KEY = "options"
MULTI_SELECT_DICTIONARY_OPTIONS_KEY = "dictionary_options"
MULTI_SELECT_OPTION_LABEL_KEY = "display_name"
MULTI_SELECT_DEFAULT_OPTION_KEY = "default"

# Accordion
ACCORDION_CONTENT_KEY = "content"
ACCORDION_LABEL_KEY = "label"
ACCORDION_ACTIVE_KEY = "active"
ACCORDION_TOGGLE_KEY = "toggle"
ACCORDION_RESET_BUTTON_KEY = "accordion-reset-button"

# Radio Box
RADIO_BOX_OPTION_KEY = "options"

# Date Time Picker
DATE_TIME_PICKER_NAME_KEY = "name"
DATE_TIME_PICKER_VALIDATOR_KEY = "validator"
DATE_TIME_PICKER_LABEL_KEY = "label"
DATE_TIME_PICKER_ACCESSOR_KEY = "accessor_function"
DATE_TIME_PICKER_HAS_PAGING_KEY = "hasPaging"

# Text Area Input
TEXT_AREA_INPUT_LABEL_KEY = "label"
TEXT_AREA_INPUT_PLACEHOLDER_KEY = "placeholder"
TEXT_AREA_INPUT_ACCESSOR_KEY = "accessor_function"
TEXT_AREA_INPUT_VALIDATOR_KEY = "validator_function"
TEXT_AREA_INPUT_URL_PARAMETER_KEY = "url_parameter"

# Accordion Reset Button
ACCORDION_RESET_LABEL_KEY = "label"
ACCORDION_RESET_BUTTON_STYLE_KEY = "button-style"
ACCORDION_RESET_MARGIN_KEY = "margin"

# Slider
SLIDER_TYPE_VALUE = "slider"
SLIDER_LABEL_KEY = "label"
SLIDER_UNIT_KEY = "unit"
SLIDER_START_KEY = "start"
SLIDER_END_KEY = "end"
SLIDER_STEP_KEY = "step"

# Block
BLOCKS_CONFIG_KEY = "blocks"
BLOCK_LABEL_LIST_KEY = "label"
BLOCK_WIDGETS_LIST_KEY = "widgets"
BLOCK_CONFIG_LABEL_KEY = "label"
BLOCK_CONFIG_WIDGETS_KEY = "components"

# Common Ui Widget Types
WIDGET_TYPE_KEY = "type"
TEXT_INPUT_TYPE_VALUE = "text_field"
MULTI_SELECT_TYPE_VALUE = "multi_select"
ACCORDION_TYPE_VALUE = "accordion"
DATE_TIME_PICKER_TYPE_VALUE = "date_time_picker"
RADIO_BOX_TYPE_VALUE = "radio_box"
TEXT_AREA_INPUT_TYPE_VALUE = "text_area_input"
ACCORDION_RESET_BUTTON_TYPE_VALUE = "accordion-reset-button"


# Fallbacks (if no key and value was given in the config yaml)
FALLBACK_UI_CONFIG_TITLE_VALUE = "Recommender Explorer"
FALLBACK_UI_CONFIG_LOGO_VALUE = ""
FALLBACK_UI_CONFIG_BACKGROUND_COLOR_VALUE = "#194569"
FALLBACK_TEXT_INPUT_LABEL_VALUE = "Default Text Label"
FALLBACK_MULTI_SELECT_OPTION_LABEL_VALUE = "Default Option Headline"
FALLBACK_MULTI_SELECT_LABEL_VALUE = "Default Multi Select Headline"
FALLBACK_ACCORDION_LABEL_VALUE = "Default Accordion Headline"
FALLBACK_DATE_TIME_PICKER_NAME_VALUE = "Default Date Time Picker Label"
FALLBACK_BLOCK_LABEL_VALUE = "Default Block Headline"
