api_prefix: $API_PREFIX
deployment_env: $DEPLOYMENT_ENVIRONMENT
opensearch:
  host: $OPENSEARCH_HOST
  port: $OPENSEARCH_PORT
  user: $OPENSEARCH_USER
  pass: $OPENSEARCH_PASS
  index: $OPENSEARCH_INDEX
