api_prefix: $API_PREFIX
base_url_search: $BASE_URL_SEARCH
base_url_ingest: $BASE_URL_INGEST
base_url_embedding: $BASE_URL_EMBEDDING
mapping_definition: $MAPPING_DEFINITION
models:
  - distiluse-base-multilingual-cased-v1: sentence-transformers/distiluse-base-multilingual-cased-v1
  - all-MiniLM-L6-v2: sentence-transformers/all-MiniLM-L6-v2
#    - german-roberta-sentence-transformer-v2: "T-Systems-onsite/german-roberta-sentence-transformer-v2"
