opensearch:
    host: $OPENSEARCH_HOST
    port: $OPENSEARCH_PORT
    user: $OPENSEARCH_USER
    pass: $OPENSEARCH_PASS
    index: $OPENSEARCH_INDEX
    field_mapping:
        "created": "availableFrom"
        "createdFormatted": "availableFrom"
        "showTitle": "showTitel"
        "crid": "externalid"
        "duration": "duration"
    mapping:
      externalId: externalid
      durationSeconds: duration
      teaserImage: teaserimage
      sophoraId: id
    restructuring: # USE THIS FOR MAPPING & RESTRUCTURING https://github.com/schibsted/jslt
      teaserImage: url
    primary_field: "sophoraId"
