api_prefix: $API_PREFIX
api_key: $API_KEY
base_url_search: $BASE_URL_SEARCH
base_url_ingest: $BASE_URL_INGEST
base_url_embedding: $BASE_URL_EMBEDDING
mapping_definition: $MAPPING_DEFINITION
dead_letter_bucket: wdr-recommender-exporter-dead-letter
models:
  - all-MiniLM-L6-v2: sentence-transformers/all-MiniLM-L6-v2
