mapping:
  '{
    id: .sophoraId,
    externalid: .externalId,
    uuid: .uuid,
    sophoraid: .sophoraId,
    type: .type,
    typeDef: .typeDef,
    title: .title,
    description: .description,
    longDescription: .longDescription,
    availableFrom: .availableFrom,
    availableTo: .availableTo,
    firstPublicationDate: .firstPublicationDate,
    keywords: .keywords,
    language: .language,
    duration: .durationSeconds,
    thematicCategories: .thematicCategories,
    genreCategory: .genreCategory,
    subgenreCategories: .subgenreCategories,
    filterCategory: .filterCategory,
    structurePath: .structurePath,
    site: .site,
    domain: .domain,
    teaserimage: .teaserImage.url,
    fskAgeRating: .fskAgeRating,
    contentRatings: .contentRatings,
    geoAvailability: .geoAvailability
    }'
