name: Microservice - Ingest

on:
  push:
    branches:
      - main
      - dev
      - SNTWREC-132-run-microservice-unit-tests-in-cicd
    paths:
      - 'microservices/ingestservice/**'

jobs:
  run_unit_tests_ingest:
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      service-name: ingest
      python-version: "3.10"
    secrets: inherit
  build_publish_deploy_ingest:
    needs: run_unit_tests_ingest
    uses: ./.github/workflows/build-publish-deploy.yml
    with:
      service-name: ingest
    secrets: inherit
