name: Microservice - Search

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'microservices/searchservice/**'

jobs:
#  run_unit_tests_search:
#    uses: ./.github/workflows/run-unit-tests.yml
#    with:
#      service-name: search
#      python-version: "3.11"
#    secrets: inherit

  build_publish_deploy_search:
 #   needs: run_unit_tests_search
    uses: ./.github/workflows/build-publish-deploy.yml
    with:
      service-name: search
    secrets: inherit
