name: Run tests

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  unit_tests:
    name: unit_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run all unit tests
        run: |
            pytest test/unit --doctest-modules --junitxml=junit/test-results.xml
